# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    mail:
        host: smtp.gmail.com
        port: 587
        username: gostroy.list@gmail.com  #Replace this field with your Gmail username.
        password: PolandWarsaw1200           #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 624054256663-o6hu4pntclth7hrietgfq589f40a4mrj.apps.googleusercontent.com
            clientSecret: NmSTAQA-rMeQReAjAXwY5Ml2

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 1822844874609538
            clientSecret: 4034ed6ac47831ddd77b768993b5f568

        # see https://apps.twitter.com/app/
        twitter:
            clientId: 710560959874646016-MGcQOk9bvy2TZHWLhY60CItFEbJyiWs
            clientSecret: xWxDTF8kkhzlGBGIWMyYsJjSzxfSQom3M9coBHcydH7YJ

        # jhipster-needle-add-social-configuration

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: goRest@localhost
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 3df3e1851109f0397050c5385e5673666e6ba887
    swagger:
        title: goRest API
        description: goRest API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
    social:
        redirectAfterSignIn: "/#/home"
